setup_dependencies:
  stage: setup
  image: ubuntu:22.04
  before_script:
    - apt-get update && apt-get install -y curl

    - curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
    - apt-get install -y nodejs
    - npm install -g npm@latest

    - /bin/bash -c "$(curl -fsSL https://php.new/install/linux/8.4)"

    - php --version
    - composer --version
    - node --version
  script:
    - npm install
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
  artifacts:
    paths:
      - vendor/
      - node_modules/
    expire_in: 1 week
