deploy:
  stage: deploy
  image: php:8.2-cli
  before_script:
    - apt-get update -yqq && apt-get install -y git unzip libpq-dev libzip-dev
    - docker-php-ext-install zip pdo pdo_pgsql
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

  script:
    - |
      echo "✅ Conexão com o Neon: ${DB_HOST}:${DB_PORT}/${DB_DATABASE}"
      php artisan db:wipe --force --database=pgsql || echo "⚠️ Pode ignorar se o banco já estiver vazio"
      php artisan migrate --force -vvv || php artisan migrate:fresh --force
      php artisan db:show
      curl -fsSL https://cli.railway.app/install.sh | sh
      ~/.railway/bin/railway login --ci
      ~/.railway/bin/railway up --detach