services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ambrosia-app
    restart: unless-stopped
    ports:
      - '80:80'
      - '5173:5173'
    volumes:
      - ./:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=agrox
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
        - postgres
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: seu_db
    ports:
      - "5432:5432"
    networks:
      - ambrosia-network

networks:
  ambrosia-network:
    driver: bridge
